/**
 * 
 */
package com.sykj.app.dao.reportForm.impl;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.sykj.app.dao.reportForm.GSQCardDao;
import com.sykj.app.model.reportForm.GSQCardM;
import com.sykj.common.dao.BaseDao;

/**
 * @author wjl 2016年1月9日 下午3:07:37
 */
@Repository("gsqCardDao")
public class GSQCardDaoImpl extends BaseDao<GSQCardM> implements GSQCardDao{

	@Override
	public List<Object> findFormList(String endTime, String cityName) {
		String citySql = "select m.id,m.shortNumber,m.shopName,n.cityName,m.ADDRESS,m.phone "
				+ "from sykj_area_shop m inner join sykj_area_city n on m.cityId = n.id "
				+ "where n.cityname in ('"+cityName+"') "
				+ "and m.shortNumber is not null and m.shortNumber != '' "
				+ "and m.shopType = '直营' "
				+ "order by shortNumber asc";
		
		String sql = "select A.shopName,IFNULL(A.cnt,0),IFNULL(B.cnt,0),IFNULL(C.cnt,0),"
				+ "IFNULL(D.cnt,0),IFNULL(E.cnt,0),IFNULL(F.cnt,0),IFNULL(G.cnt,0),"
				+ "IFNULL(H.cnt,0),IFNULL(I.cnt,0),IFNULL(K.cnt,0) from "
				+ "(select t2.shopName shopName,t1.cnt cnt "
				+ "from ("+citySql+") t2 left join "
				+ "(select companyCode,count(*) cnt from sykj_erp_unboundcard "
				+ "where memberCardTypeCode in ('2016.01.001','2016.01.003') "
				+ "and DATE_FORMAT(saleDate,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by companyCode) t1 on t1.companyCode = t2.shortnumber) A "
				+ "inner join "
				+ "(select t2.shopName shopName,t1.cnt cnt "
				+ "from ("+citySql+") t2 left join "
				+ "(select A.companycode,count(*) cnt from "
				+ "(select companycode,mobile,count(*) cnt from sykj_erp_unboundcard "
				+ "where memberCardTypeCode in ('2016.01.001','2016.01.003') "
				+ "and DATE_FORMAT(saleDate,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by companycode,mobile) A "
				+ "group by A.companycode) t1 on t1.companyCode = t2.shortnumber) B on A.shopName=B.shopName "
				+ "inner join "
				+ "(select k.shopName shopName,j.cnt cnt from "
				+ "("+citySql+") k left join "
				+ "(select DATE_FORMAT(t1.useTime,'%Y-%m-%d') date,shopId,count(*) cnt from sykj_savings_itemgiveuse t1 "
				+ "inner join sykj_savings_itemgive t2 on t1.itemgiveId = t2.id "
				+ "inner join sykj_savings_usercard t3 on t2.userCardId = t3.id "
				+ "where t3.status = 3 and t3.cityGroup in ('gz','sh') "
				+ "and DATE_FORMAT(t1.useTime,'%Y-%m-%d') < '"+endTime+"' "
				+ "and totalMoney != 0 group by shopId "
				+ "order by DATE_FORMAT(t1.useTime,'%Y-%m-%d') desc,shopId desc,cnt desc) j on k.id = j.shopId) C "
				+ "on C.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname shopName,d.cnt cnt "
				+ "from ("+citySql+") a left join "
				+ "(select b.code,count(*) cnt from "
				+ "(select t3.companycode code,t2.mobile mobile,t1.* from sykj_savings_itemgive t1 "
				+ "inner join sykj_user_userinformation t2 on t1.fromOpenId = t2.openId "
				+ "left join (select * from sykj_erp_unboundcard group by mobile) t3 on t2.mobile = t3.mobile "
				+ "where t1.itemId = '970096a2-d0bb-4441-ad77-52237456fdb9' and t1.status in ('1','2') "
				+ "and t2.MOBILE is not null "
				+ "and DATE_FORMAT(t1.senddatetime,'%Y-%m-%d') < '"+endTime+"' "
				+ ") b group by b.code order by b.code asc) d "
				+ "on a.shortnumber = d.code) D on D.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname shopName,d.cnt cnt "
				+ "from ("+citySql+") a left join "
				+ "(select b.code,count(*) cnt from "
				+ "(select t3.companycode code,t2.mobile mobile,t1.* from sykj_savings_itemgive t1 "
				+ "inner join sykj_user_userinformation t2 on t1.fromOpenId = t2.openId "
				+ "left join (select * from sykj_erp_unboundcard group by mobile) t3 on t2.mobile = t3.mobile "
				+ "where t1.itemId = '970096a2-d0bb-4441-ad77-52237456fdb9' and t1.status in ('1','2') and t2.MOBILE is not null "
				+ "and DATE_FORMAT(t1.senddatetime,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by t1.fromOpenId) b group by b.code "
				+ "order by b.code asc) d on A.shortnumber = d.code) E on E.shopName = A.shopName "
				+ "inner join "
				+ "(select t1.shopname shopName,t2.cnt cnt from "
				+ "("+citySql+") t1 left join "
				+ "(select shopid,count(*) cnt "
				+ "from sykj_savings_itemgiveuse t1 inner join sykj_savings_itemgive t2 on t1.itemgiveId = t2.id "
				+ "where t2.itemId = '970096a2-d0bb-4441-ad77-52237456fdb9' and t1.status = 1 "
				+ "and DATE_FORMAT(t1.usetime,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by t1.shopid) t2 on t1.id = t2.shopid) F on F.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname shopName,b.cnt cnt from "
				+ "("+citySql+") a left join "
				+ "(select t2.companyCode code,count(*) cnt from "
				+ "(select DISTINCT mobile,companyCode from sykj_erp_unboundcard) t2 "
				+ "inner join sykj_user_userinformation t3 on t3.mobile = t2.mobile "
				+ "inner join sykj_luckdraw_userprize t4 on t3.openid = t4.userOpenId "
				+ "where DATE_FORMAT(t4.winningTime,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by t2.companyCode) b on a.shortnumber = b.code ) G on G.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname shopName,b.cnt cnt from "
				+ "("+citySql+") a left join "
				+ "(select t2.companyCode code,count(*) cnt from "
				+ "(select DISTINCT mobile,companyCode from sykj_erp_unboundcard) t2 "
				+ "inner join sykj_user_userinformation t3 on t3.mobile = t2.mobile "
				+ "inner join (select DISTINCT useropenid "
				+ "from sykj_luckdraw_userprize where DATE_FORMAT(winningTime,'%Y-%m-%d') < '"+endTime+"' ) t4 "
				+ "on t3.openid = t4.userOpenId "
				+ "group by t2.companyCode) b on a.shortnumber = b.code ) H on H.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname shopName,b.cnt cnt from "
				+ "("+citySql+") a left join "
				+ "(select t3.companycode,count(*) cnt from "
				+ "(select * from sykj_erp_unboundcard group by mobile) t3 "
				+ "inner join sykj_user_userinformation t2 on t2.mobile = t3.mobile "
				+ "inner join sykj_savings_usercarditem t1 on t1.openid = t2.openid "
				+ "where t1.itemid = '970096a2-d0bb-4441-ad77-52237456fdb9' and t1.status = 0 "
				+ "and DATE_FORMAT(t1.CREATETIME,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by t3.companycode) b "
				+ "on a.shortnumber = b.companycode ) I on I.shopName = A.shopName "
				+ "inner join "
				+ "(select k.shopName shopName,j.cnt cnt from "
				+ "("+citySql+") k left join "
				+ "(select z.shopid,count(*) cnt from ("
				+ "select DATE_FORMAT(t1.useTime,'%Y-%m-%d') date,shopId,t1.userOpenId,count(*) cnt from sykj_savings_itemgiveuse t1 "
				+ "inner join sykj_savings_itemgive t2 on t1.itemgiveId = t2.id "
				+ "inner join sykj_savings_usercard t3 on t2.userCardId = t3.id "
				+ "where t3.status = 3 and t3.cityGroup in ('gz','sh') "
				+ "and DATE_FORMAT(t1.useTime,'%Y-%m-%d') < '"+endTime+"' "
				+ "and totalMoney != 0 "
				+ "group by shopId,t1.userOpenId "
				+ "order by DATE_FORMAT(t1.useTime,'%Y-%m-%d') desc,shopId desc,cnt desc "
				+ ") z group by z.shopId "
				+ ") j on k.id = j.shopId "
				+ ") K on K.SHOPNAME = A.SHOPNAME";
		System.out.println("citySql="+citySql);
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

	@Override
	public List<Object> findzzfFormList(String endTime, String cityName) {
		// TODO Auto-generated method stub
		String citySql = "select m.id,m.shortNumber,m.shopName,n.cityName from sykj_area_shop m "
				+ "inner join sykj_area_city n on m.cityId = n.id "
				+ "where n.cityname in ('"+cityName+"') "
				+ "and m.shortNumber is not null and m.shortNumber != '' "
				+ "and m.shopType = '直营' "
				+ "and m.id != '622' "
				+ "order by shortNumber asc";
		
		String sql = "select A.shopName,IFNULL(A.cnt,0),IFNULL(B.cnt,0),IFNULL(C.cnt,0),"
				+ "IFNULL(D.cnt,0),IFNULL(E.cnt,0),IFNULL(F.cnt,0),IFNULL(G.cnt,0),IFNULL(K.cnt,0)from "
				+ "(select t2.shopName shopName,t1.cnt cnt "
				+ "from ("+citySql+") t2 left join "
				+ "(select companyCode,count(*) cnt from sykj_erp_unboundcard "
				+ "where memberCardTypeCode in ('2015.11.002','2015.11.003','2015.11.004','2015.11.006') "
				+ "and DATE_FORMAT(saleDate,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by companyCode) t1 on t1.companyCode = t2.shortnumber) A "
				+ "inner join "
				+ "(select t2.shopName shopName,t1.cnt cnt "
				+ "from ("+citySql+") t2 left join "
				+ "(select a.companycode,count(*) cnt from "
				+ "(select companycode,mobile,count(*) cnt from sykj_erp_unboundcard "
				+ "where memberCardTypeCode in ('2015.11.002','2015.11.003','2015.11.004','2015.11.006') "
				+ "and DATE_FORMAT(saleDate,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by companycode,mobile) a "
				+ "group by a.companycode) t1 on t1.companyCode = t2.shortnumber) B on B.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopName shopName,B.cnt cnt from "
				+ "("+citySql+") a left join "
				+ "(select DATE_FORMAT(t1.useTime,'%Y-%m-%d') date,shopId,count(*) cnt "
				+ "from sykj_savings_itemgiveuse t1 "
				+ "inner join sykj_savings_itemgive t2 on t1.itemgiveId = t2.id "
				+ "inner join sykj_savings_usercard t3 on t2.userCardId = t3.id "
				+ "where t3.status = 3 and t3.cityGroup in ('zzf') "
				+ "and DATE_FORMAT(t1.useTime,'%Y-%m-%d') < '"+endTime+"' "
				+ "and totalMoney != 0 "
				+ "group by shopId order by DATE_FORMAT(t1.useTime,'%Y-%m-%d') desc,shopId desc,cnt desc) b "
				+ "on a.id = b.shopId) C on C.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname,d.cnt "
				+ "from ("+citySql+") a left join "
				+ "(select b.code,count(*) cnt from "
				+ "(select t3.companycode code,t2.mobile mobile,t1.* from sykj_savings_itemgive t1 "
				+ "inner join sykj_user_userinformation t2 on t1.fromOpenId = t2.openId "
				+ "left join (select * from sykj_erp_unboundcard group by mobile) t3 on t2.mobile = t3.mobile "
				+ "where t1.itemId = 'f9aed2e7-9f1e-4dd4-85a2-123456790' and t1.status in ('0','1','2') and t2.MOBILE is not null "
				+ "and DATE_FORMAT(t1.senddatetime,'%Y-%m-%d') < '"+endTime+"' ) b "
				+ "group by b.code order by b.code asc) d "
				+ "on a.shortnumber = d.code) D on D.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname,d.cnt "
				+ "from ("+citySql+") a left join "
				+ "(select b.code,count(*) cnt from "
				+ "(select t3.companycode code,t2.mobile mobile,t1.* from sykj_savings_itemgive t1 "
				+ "inner join sykj_user_userinformation t2 on t1.fromOpenId = t2.openId "
				+ "left join (select * from sykj_erp_unboundcard group by mobile) t3 on t2.mobile = t3.mobile "
				+ "where t1.itemId = 'f9aed2e7-9f1e-4dd4-85a2-123456790' and t1.status in ('0','1','2') and t2.MOBILE is not null "
				+ "and DATE_FORMAT(t1.senddatetime,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by t1.fromOpenId) b group by b.code order by b.code asc) d "
				+ "on a.shortnumber = d.code) E on E.shopName = A.shopName "
				+ "inner join "
				+ "(select t1.shopname,t2.cnt from "
				+ "("+citySql+") t1 left join "
				+ "(select shopid,count(*) cnt "
				+ "from sykj_savings_itemgiveuse t1 inner join sykj_savings_itemgive t2 on t1.itemgiveId = t2.id "
				+ "where t2.itemId = 'f9aed2e7-9f1e-4dd4-85a2-123456790' and t1.status = 1 "
				+ "and DATE_FORMAT(t1.usetime,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by t1.shopid) t2 on t1.id = t2.shopid ) F on F.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname,b.cnt from "
				+ "("+citySql+") a left join "
				+ "(select t3.companycode,count(*) cnt from "
				+ "(select * from sykj_erp_unboundcard group by mobile) t3 "
				+ "inner join sykj_user_userinformation t2 on t2.mobile = t3.mobile "
				+ "inner join sykj_savings_usercarditem t1 on t1.openid = t2.openid "
				+ "where t1.itemid = 'f9aed2e7-9f1e-4dd4-85a2-123456790' and t1.status = 0 "
				+ "and DATE_FORMAT(t1.CREATETIME,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by t3.companycode) b on a.shortnumber = b.companycode) G on G.shopName = A.shopName "
				+ "inner join "
				+ "(select k.shopName shopName,j.cnt cnt from "
				+ "("+citySql+") k left join "
				+ "(select z.shopid,count(*) cnt from ("
				+ "select DATE_FORMAT(t1.useTime,'%Y-%m-%d') date,shopId,t1.userOpenId,count(*) cnt from sykj_savings_itemgiveuse t1 "
				+ "inner join sykj_savings_itemgive t2 on t1.itemgiveId = t2.id "
				+ "inner join sykj_savings_usercard t3 on t2.userCardId = t3.id "
				+ "where t3.status = 3 and t3.cityGroup in ('zzf') "
				+ "and DATE_FORMAT(t1.useTime,'%Y-%m-%d') < '"+endTime+"' "
				+ "and totalMoney != 0 "
				+ "group by shopId,t1.userOpenId "
				+ "order by DATE_FORMAT(t1.useTime,'%Y-%m-%d') desc,shopId desc,cnt desc "
				+ ") z group by z.shopId "
				+ ") j on k.id = j.shopId "
				+ ") K on K.SHOPNAME = A.SHOPNAME";
		System.out.println("citySql="+citySql);
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

	@Override
	public List<Object> findRoseFormList(String beginTime, String endTime,String cityName) {
		// TODO Auto-generated method stub
		String citySql = "select m.id,m.shortNumber,m.shopName,n.cityName from sykj_area_shop m "
				+ "inner join sykj_area_city n on m.cityId = n.id "
				+ "where n.cityname in ('"+cityName+"') "
				+ "and m.shortNumber is not null and m.shortNumber != '' "
				+ "order by shortNumber asc";
		
		String sql = "select A.time,IFNULL(B.cnt,0),IFNULL(C.cnt,0),IFNULL(D.cnt,0),IFNULL(E.cnt,0),"
				+ "IFNULL(F.cnt,0),IFNULL(G.cnt,0),IFNULL(H.cnt,0),"
				+ "IFNULL(I.cnt,0),IFNULL(J.cnt,0),IFNULL(K.cnt,0),IFNULL(L.cnt,0) from "
				+ "(select DATE_FORMAT(createtime,'%Y-%m-%d') time from sykj_savings_usercarditem "
				+ "where DATE_FORMAT(createtime,'%Y-%m-%d') >= '"+beginTime+"' and DATE_FORMAT(createtime,'%Y-%m-%d') < '"+endTime+"'"
				+ "group by DATE_FORMAT(createtime,'%Y-%m-%d') order by createtime desc) A "
				+ "left join "
				+ "(select DATE_FORMAT(t1.CREATEDATETIME, '%Y-%m-%d') time, count(t2.mobile) cnt "
				+ "from sykj_user_tuser t1 "
				+ "inner join sykj_user_userinformation t2 on t1.id = t2.userid "
				+ "left join (select mobile,companyCode from sykj_erp_unboundcard group by mobile) t3 "
				+ "on t3.mobile = t2.mobile "
				+ "left join ("+citySql+") t4 on t4.shortnumber = t3.companycode "
				+ "where t4.cityname is not null "
				+ "GROUP BY DATE_FORMAT( t1.CREATEDATETIME, '%Y-%m-%d' ) desc,t4.cityname) B on B.time = A.time "
				+ "left join "
				+ "(select DATE_FORMAT(t1.winningTime,'%Y-%m-%d') time,count(*) cnt from sykj_luckdraw_userprize t1 "
				+ "inner join sykj_user_userinformation t2 on t1.useropenid = t2.openId "
				+ "left join (select mobile,companyCode from sykj_erp_unboundcard group by mobile) t3 "
				+ "on t3.mobile = t2.mobile "
				+ "left join ("+citySql+") t4 on t4.shortnumber = t3.companyCode "
				+ "where t1.fromtype = '玫瑰女人节' and DATE_FORMAT(t1.winningTime,'%Y-%m-%d') < '"+endTime+"' "
				+ "and t4.cityname is not null "
				+ "group by DATE_FORMAT(t1.winningTime,'%Y-%m-%d') desc,t4.cityname) C on C.time = A.time "
				+ "left join "
				+ "(select DATE_FORMAT(t1.buyDateTime,'%Y-%m-%d') time,count(*) cnt from sykj_savings_usercard t1  "
				+ "inner join sykj_savings_itemgive t2 on t1.id = t2.userCardId "
				+ "inner join sykj_savings_itemgiveuse t3 on t3.itemgiveId = t2.id "
				+ "left join ("+citySql+") t4 on t3.shopId = t4.id "
				+ "where t1.cardid in ('b55e7143-4043-41c7-8447-73abab6fa9ef','iuioe33f-542d-4629-ab83-383838ww69') and t1.status = 3 "
				+ "and t4.cityname is not null "
				+ "group by DATE_FORMAT(t1.buyDateTime,'%Y-%m-%d') desc,t4.cityname) D on D.time = A.time "
				+ "left join "
				+ "(select DATE_FORMAT(t1.createtime,'%Y-%m-%d') time,count(*) cnt "
				+ "from (select mobile,companycode,createtime from sykj_erp_unboundcard "
				+ "where membercardtypecode in ('2016.02.003') "
				+ "and membercardcode not in (select membercardcode from sykj_tempmembercardcode) "
				+ "group by mobile,companycode order by createtime asc) t1 "
				+ "inner join ("+citySql+") t2 on t1.companycode = t2.shortnumber "
				+ "where t2.cityname is not null "
				+ "group by DATE_FORMAT(t1.createtime,'%Y-%m-%d') desc,t2.cityname) E on E.time = A.time "
				+ "left join "
				+ "(SELECT DATE_FORMAT(t1.createtime,'%Y-%m-%d') time ,count(*) cnt "
				+ "from sykj_savings_usercarditem t1 "
				+ "inner join sykj_user_userinformation t2 on t1.openid = t2.openid "
				+ "left join (select mobile,companycode from sykj_erp_unboundcard group by mobile ORDER BY createtime asc) t3 on t3.mobile = t2.mobile "
				+ "left join ("+citySql+") t4 on t4.shortnumber = t3.companycode "
				+ "where t1.itemid = '83b94b27-7c1a-48fc-a136-04a745aa39b3' and t4.cityname is not null "
				+ "group by DATE_FORMAT(t1.createtime,'%Y-%m-%d') desc,t4.cityname) F on F.time = A.time "
				+ "left join "
				+ "(select DATE_FORMAT(t2.updatedatetime,'%Y-%m-%d') time,count(*) cnt from sykj_savings_usercarditem t1 "
				+ "left join sykj_savings_itemgive t2 on t1.id = t2.userCardId "
				+ "left join sykj_user_userinformation t3 on t2.toOpenId = t3.openid "
				+ "left join (select mobile,companycode from sykj_erp_unboundcard group by mobile ORDER BY createtime asc ) t4 on t4.mobile = t3.mobile "
				+ "left join ("+citySql+") t6 on "
				+ "t6.shortnumber = t4.companyCode "
				+ "where t1.itemid in ('83b94b27-7c1a-48fc-a136-04a745aa39b3') "
				+ "and t2.status in (1,2) and t2.sendDateTime is not null and t2.updateDateTime is not null "
				+ "and t6.cityname is not null "
				+ "group by DATE_FORMAT(t2.updatedatetime,'%Y-%m-%d') desc,t6.cityname) G on G.time = A.time "
				+ "left join "
				+ "(select DATE_FORMAT(t3.usetime,'%Y-%m-%d') time,count(*) cnt "
				+ "from sykj_savings_usercarditem t1  "
				+ "inner join sykj_savings_itemgive t2 on t1.id = t2.usercardid  "
				+ "inner join sykj_savings_itemgiveuse t3 on t3.itemgiveid = t2.ID "
				+ "left join ("+citySql+") t4 on t4.id = t3.shopid "
				+ "where t1.itemid = '83b94b27-7c1a-48fc-a136-04a745aa39b3' and t3.status = 1 "
				+ "and t4.cityname is not null "
				+ "group by DATE_FORMAT(t3.usetime,'%Y-%m-%d') desc,t4.cityname) H on H.time = A.time "
				+ "left join "
				+ "(select DATE_FORMAT(t1.buyDateTime,'%Y-%m-%d') time,count(*) cnt from sykj_savings_usercard t1 "
				+ "inner join sykj_savings_itemgive t2 on t1.id = t2.userCardId "
				+ "inner join sykj_savings_itemgiveuse t3 on t3.itemgiveId = t2.id "
				+ "left join ("+citySql+") t4 on t3.shopId = t4.id "
				+ "where t1.cardid = 'iuioe33f-542d-4629-ab83-989898ww198' and t1.status = 3 and t4.cityname is not null "
				+ "group by DATE_FORMAT(t1.buyDateTime,'%Y-%m-%d') desc,t4.cityname) I on I.time = A.time "
				+ "left join "
				+ "(select DATE_FORMAT(t1.createtime,'%Y-%m-%d') time,count(*) cnt "
				+ "from (select mobile,companycode,createtime from sykj_erp_unboundcard  "
				+ "where membercardtypecode in ('2016.02.001') group by mobile,companycode order by createtime asc) t1  "
				+ "inner join ("+citySql+") t2 on t1.companycode = t2.shortnumber  "
				+ "where t2.cityname is not null "
				+ "group by DATE_FORMAT(t1.createtime,'%Y-%m-%d') desc,t2.cityname) J on J.time = A.time "
				+ "left join "
				+ "(select DATE_FORMAT(t2.updatedatetime,'%Y-%m-%d') time,count(*) cnt from sykj_savings_usercard t1 "
				+ "left join sykj_savings_itemgive t2 on t1.fromUserCardId = t2.userCardId "
				+ "left join sykj_user_userinformation t3 on t2.toOpenId = t3.openid "
				+ "left join (select mobile,companycode from sykj_erp_unboundcard group by mobile ORDER BY createtime asc ) t4 on t4.mobile = t3.mobile "
				+ "left join ("+citySql+") t6 on t6.shortnumber = t4.companyCode "
				+ "where t1.cardid = 'iuioe33f-542d-4629-ab83-989898ww198' and t2.status in (1,2) and t1.fromOpenId is not null "
				+ "and t6.cityname is not null "
				+ "group by DATE_FORMAT(t2.updatedatetime,'%Y-%m-%d') desc,t6.cityname) K on K.time = A.time "
				+ "left join "
				+ "(select DATE_FORMAT(t3.usetime,'%Y-%m-%d') time,count(*) cnt "
				+ "from sykj_savings_usercard t1 "
				+ "inner join sykj_savings_itemgive t2 on t1.id = t2.usercardid "
				+ "inner join sykj_savings_itemgiveuse t3 on t3.itemgiveid = t2.ID "
				+ "left join ("+citySql+") t4 on t4.id = t3.shopid "
				+ "where t1.cardid = 'iuioe33f-542d-4629-ab83-989898ww198' and t3.status = 1 "
				+ "and t4.cityname is not null "
				+ "group by DATE_FORMAT(t3.usetime,'%Y-%m-%d') desc,t4.cityname) L on L.time = A.time";
		
		System.out.println("citySql="+citySql);
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

	@Override
	public List<Object> findBtsxcyFormList(String endTime, String cityName) {
		// TODO Auto-generated method stub
		String citySql = "select m.id,m.shortNumber,m.shopName,n.cityName,m.ADDRESS,m.phone "
				+ "from sykj_area_shop m inner join sykj_area_city n on m.cityId = n.id "
				+ "where n.cityname in ('"+cityName+"') "
				+ "and m.shortNumber is not null and m.shortNumber != '' "
				+ "and m.shopType = '直营' and m.id != '26e44c9c-1a0e-41a3-9678-766f71c3b308' "
				+ "order by shortNumber asc";
		String sql = "select A.shopName,IFNULL(A.cnt,0),IFNULL(B.cnt,0),IFNULL(C.cnt,0),IFNULL(D.cnt,0),"
				+ "IFNULL(E.cnt,0),IFNULL(F.cnt,0),IFNULL(G.cnt,0),IFNULL(H.cnt,0),IFNULL(I.cnt,0),IFNULL(K.cnt,0) from "
				+ "(select t2.shopName shopName,t1.cnt cnt "
				+ "from ("+citySql+") t2 left join "
				+ "(select companyCode,count(*) cnt from sykj_erp_unboundcard "
				+ "where memberCardTypeCode in ('2016.01.001','2016.01.003') "
				+ "and DATE_FORMAT(saleDate,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by companyCode) t1 on t1.companyCode = t2.shortnumber) A "
				+ "inner join "
				+ "(select t2.shopName shopName,t1.cnt cnt "
				+ "from ("+citySql+") t2 left join "
				+ "(select A.companycode,count(*) cnt from "
				+ "(select companycode,mobile,count(*) cnt from sykj_erp_unboundcard "
				+ "where memberCardTypeCode in ('2016.01.001','2016.01.003') "
				+ "and DATE_FORMAT(saleDate,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by companycode,mobile) A group by A.companycode) t1 "
				+ "on t1.companyCode = t2.shortnumber) B on A.shopName=B.shopName "
				+ "inner join (select k.shopName shopName,j.cnt cnt "
				+ "from ("+citySql+") k left join "
				+ "(select DATE_FORMAT(t1.useTime,'%Y-%m-%d') date,shopId,count(*) cnt "
				+ "from sykj_savings_itemgiveuse t1 "
				+ "inner join sykj_savings_itemgive t2 on t1.itemgiveId = t2.id "
				+ "inner join sykj_savings_usercard t3 on t2.userCardId = t3.id "
				+ "where t3.status = 3 and t3.cityGroup in ('bt','hu','xa','cy') "
				+ "and DATE_FORMAT(t1.useTime,'%Y-%m-%d') < '"+endTime+"' "
				+ "and totalMoney != 0 "
				+ "group by shopId order by DATE_FORMAT(t1.useTime,'%Y-%m-%d') desc,shopId desc,cnt desc) j "
				+ "on k.id = j.shopId) C on C.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname shopName,d.cnt cnt "
				+ "from ("+citySql+") a left join "
				+ "(select b.code,count(*) cnt from "
				+ "(select t3.companycode code,t2.mobile mobile,t1.* from sykj_savings_itemgive t1 "
				+ "inner join sykj_user_userinformation t2 on t1.fromOpenId = t2.openId "
				+ "left join (select * from sykj_erp_unboundcard group by mobile) t3 on t2.mobile = t3.mobile "
				+ "where t1.itemId = 'bcc99c4b-5b6c-49a8-b6db-e5770c430a2f' "
				+ "and t1.status in ('1','2') and t2.MOBILE is not null "
				+ "and DATE_FORMAT(t1.senddatetime,'%Y-%m-%d') < '"+endTime+"' ) b "
				+ "group by b.code order by b.code asc) d on a.shortnumber = d.code) D on D.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname shopName,d.cnt cnt "
				+ "from ("+citySql+") a left join "
				+ "(select b.code,count(*) cnt from "
				+ "(select t3.companycode code,t2.mobile mobile,t1.* from sykj_savings_itemgive t1 "
				+ "inner join sykj_user_userinformation t2 on t1.fromOpenId = t2.openId "
				+ "left join (select * from sykj_erp_unboundcard group by mobile) t3 on t2.mobile = t3.mobile "
				+ "where t1.itemId = 'bcc99c4b-5b6c-49a8-b6db-e5770c430a2f' "
				+ "and t1.status in ('1','2') and t2.MOBILE is not null "
				+ "and DATE_FORMAT(t1.senddatetime,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by t1.fromOpenId) b group by b.code "
				+ "order by b.code asc) d on A.shortnumber = d.code) E on E.shopName = A.shopName "
				+ "inner join "
				+ "(select t1.shopname shopName,t2.cnt cnt "
				+ "from ("+citySql+") t1 left join "
				+ "(select shopid,count(*) cnt "
				+ "from sykj_savings_itemgiveuse t1 inner join sykj_savings_itemgive t2 on t1.itemgiveId = t2.id "
				+ "where t2.itemId = 'bcc99c4b-5b6c-49a8-b6db-e5770c430a2f' and t1.status = 1 "
				+ "and DATE_FORMAT(t1.usetime,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by t1.shopid) t2 on t1.id = t2.shopid) F on F.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname shopName,b.cnt cnt "
				+ "from ("+citySql+") a left join "
				+ "(select t2.companyCode code,count(*) cnt from "
				+ "(select DISTINCT mobile,companyCode from sykj_erp_unboundcard) t2 "
				+ "inner join sykj_user_userinformation t3 on t3.mobile = t2.mobile "
				+ "inner join sykj_luckdraw_userprize t4 on t3.openid = t4.userOpenId "
				+ "where DATE_FORMAT(t4.winningTime,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by t2.companyCode) b on a.shortnumber = b.code ) G on G.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname shopName,b.cnt cnt "
				+ "from ("+citySql+") a left join "
				+ "(select t2.companyCode code,count(*) cnt from "
				+ "(select DISTINCT mobile,companyCode from sykj_erp_unboundcard) t2 "
				+ "inner join sykj_user_userinformation t3 on t3.mobile = t2.mobile "
				+ "inner join (select DISTINCT useropenid "
				+ "from sykj_luckdraw_userprize where DATE_FORMAT(winningTime,'%Y-%m-%d') < '"+endTime+"' ) t4 "
				+ "on t3.openid = t4.userOpenId "
				+ "group by t2.companyCode) b on a.shortnumber = b.code ) H on H.shopName = A.shopName "
				+ "inner join "
				+ "(select a.shopname shopName,b.cnt cnt "
				+ "from ("+citySql+") a left join "
				+ "(select t3.companycode,count(*) cnt from "
				+ "(select * from sykj_erp_unboundcard group by mobile) t3 "
				+ "inner join sykj_user_userinformation t2 on t2.mobile = t3.mobile  "
				+ "inner join sykj_savings_usercarditem t1 on t1.openid = t2.openid "
				+ "where t1.itemid = 'bcc99c4b-5b6c-49a8-b6db-e5770c430a2f' and t1.status = 0 "
				+ "and DATE_FORMAT(t1.CREATETIME,'%Y-%m-%d') < '"+endTime+"' "
				+ "group by t3.companycode) b on a.shortnumber = b.companycode ) I on I.shopName = A.shopName "
				+ "inner join "
				+ "(select k.shopName shopName,j.cnt cnt from "
				+ "("+citySql+") k left join "
				+ "(select z.shopid,count(*) cnt from ("
				+ "select DATE_FORMAT(t1.useTime,'%Y-%m-%d') date,shopId,t1.userOpenId,count(*) cnt from sykj_savings_itemgiveuse t1 "
				+ "inner join sykj_savings_itemgive t2 on t1.itemgiveId = t2.id "
				+ "inner join sykj_savings_usercard t3 on t2.userCardId = t3.id "
				+ "where t3.status = 3 and t3.cityGroup in ('bt','hu','xa','cy') "
				+ "and DATE_FORMAT(t1.useTime,'%Y-%m-%d') < '"+endTime+"' "
				+ "and totalMoney != 0 "
				+ "group by shopId,t1.userOpenId "
				+ "order by DATE_FORMAT(t1.useTime,'%Y-%m-%d') desc,shopId desc,cnt desc "
				+ ") z group by z.shopId "
				+ ") j on k.id = j.shopId "
				+ ") K on K.SHOPNAME = A.SHOPNAME";
		System.out.println("citySql="+citySql);
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

	@Override
	public List<Object> roseBuy() {
		// TODO Auto-generated method stub
		String sql = "select K.time,"
				+ "IFNULL(N.珠海市,0),IFNULL(N.中山市,0),IFNULL(N.佛山市,0),"
				+ "IFNULL(N.广州市,0),IFNULL(N.深圳市,0),IFNULL(N.海口市,0),"
				+ "IFNULL(N.北京市,0),IFNULL(N.天津市,0),IFNULL(N.上海市,0),"
				+ "IFNULL(N.西安市,0),IFNULL(N.成都市,0),IFNULL(N.重庆市,0),"
				+ "IFNULL(M.珠海市,0),IFNULL(M.中山市,0),IFNULL(M.佛山市,0),"
				+ "IFNULL(M.广州市,0),IFNULL(M.深圳市,0),IFNULL(M.海口市,0),"
				+ "IFNULL(M.北京市,0),IFNULL(M.天津市,0),IFNULL(M.上海市,0),"
				+ "IFNULL(M.西安市,0),IFNULL(M.成都市,0),IFNULL(M.重庆市,0) "
				+ "from "
				+ "(select DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') time from sykj_user_tuser "
				+ "where DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') > '2016-02-26' and DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') < DATE_FORMAT(SYSDATE(),'%Y-%m-%d') "
				+ "group by DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') "
				+ "ORDER BY DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') desc) K "
				+ "left join "
				+ "(select d as time ,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',"
				+ "sum(if(cn='佛山市',cnt,0)) as '佛山市',sum(if(cn='广州市',cnt,0)) as '广州市',"
				+ "sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',"
				+ "sum(if(cn='上海市',cnt,0)) as '上海市',sum(if(cn='西安市',cnt,0)) as '西安市',"
				+ "sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "from "
				+ "(select DATE_FORMAT(t1.createtime,'%Y-%m-%d') d,t3.cityname cn,count(*) cnt "
				+ "from (select t.mobile,t.companycode,t.createtime from "
				+ "(select * from sykj_erp_unboundcard where membercardtypecode = '2016.02.003' and membercardcode not in "
				+ "(select membercardcode from sykj_tempmembercardcode) "
				+ "order by createtime asc) t "
				+ "group by t.mobile,t.companycode,t.createtime) t1 "
				+ "inner join sykj_area_shop t2 on t1.companycode = t2.shortnumber "
				+ "inner join sykj_area_city t3 on t3.id = t2.cityid "
				+ "group by DATE_FORMAT(t1.createtime,'%Y-%m-%d'),t3.cityname) A "
				+ "group by A.d "
				+ "order by A.d desc) M on K.time = M.time "
				+ "left JOIN "
				+ "(select d as time,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',"
				+ "sum(if(cn='佛山市',cnt,0)) as '佛山市',sum(if(cn='广州市',cnt,0)) as '广州市',"
				+ "sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',"
				+ "sum(if(cn='上海市',cnt,0)) as '上海市',sum(if(cn='西安市',cnt,0)) as '西安市',"
				+ "sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "from (select DATE_FORMAT(t.buydatetime,'%Y-%m-%d') d,t5.cityname cn,count(*) cnt from sykj_savings_usercard t "
				+ "inner join sykj_savings_itemgive t2 on t.id = t2.userCardId "
				+ "inner join sykj_savings_itemgiveuse t3 on t2.id = t3.itemgiveId "
				+ "inner join sykj_area_shop t4 on t4.id = t3.shopId "
				+ "inner join sykj_area_city t5 on t5.id = t4.cityid "
				+ "where t.cardid in ('b55e7143-4043-41c7-8447-73abab6fa9ef','iuioe33f-542d-4629-ab83-383838ww69') "
				+ "and t.fromOpenId is null and t.status = 3 "
				+ "group by DATE_FORMAT(t.buydatetime,'%Y-%m-%d'),t5.cityname) A "
				+ "group by A.d "
				+ "order by A.d desc) N on K.time = N.time";
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

	@Override
	public List<Object> roseSend() {
		// TODO Auto-generated method stub
		String sql = "select J.*,"
				+ "IFNULL(K.珠海市,0),IFNULL(K.中山市,0),IFNULL(K.佛山市,0),IFNULL(K.广州市,0),"
				+ "IFNULL(K.深圳市,0),IFNULL(K.海口市,0),IFNULL(K.北京市,0),IFNULL(K.天津市,0),"
				+ "IFNULL(K.上海市,0),IFNULL(K.西安市,0),IFNULL(K.成都市,0),IFNULL(K.重庆市,0),"
				+ "IFNULL(L.珠海市,0),IFNULL(L.中山市,0),IFNULL(L.佛山市,0),IFNULL(L.广州市,0),"
				+ "IFNULL(L.深圳市,0),IFNULL(L.海口市,0),IFNULL(L.北京市,0),IFNULL(L.天津市,0),"
				+ "IFNULL(L.上海市,0),IFNULL(L.西安市,0),IFNULL(L.成都市,0),IFNULL(L.重庆市,0) "
				+ "from "
				+ "(select d as time ,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',"
				+ "sum(if(cn='佛山市',cnt,0)) as '佛山市',sum(if(cn='广州市',cnt,0)) as '广州市',"
				+ "sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',"
				+ "sum(if(cn='上海市',cnt,0)) as '上海市',sum(if(cn='西安市',cnt,0)) as '西安市',"
				+ "sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "FROM "
				+ "(select DATE_FORMAT(t.createtime,'%Y-%m-%d') d,t3.cityname cn,count(*) cnt from sykj_savings_usercarditem t "
				+ "inner join sykj_area_shop t2 on t2.shortnumber = SUBSTRING_INDEX(SUBSTRING(t.fldMemberCardTypeCode,13),'-',1) "
				+ "inner join sykj_area_city t3 on t3.id = t2.cityid "
				+ "where t.itemid = '83b94b27-7c1a-48fc-a136-04a745aa39b3' "
				+ "group by DATE_FORMAT(t.createtime,'%Y-%m-%d'),t3.cityname) A "
				+ "group by A.d "
				+ "order by A.d desc) J "
				+ "left join "
				+ "(select d as time,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',"
				+ "sum(if(cn='佛山市',cnt,0)) as '佛山市',sum(if(cn='广州市',cnt,0)) as '广州市',"
				+ "sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',"
				+ "sum(if(cn='上海市',cnt,0)) as '上海市',sum(if(cn='西安市',cnt,0)) as '西安市',"
				+ "sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "FROM "
				+ "(SELECT DATE_FORMAT(t.updatedatetime,'%Y-%m-%d') d,t4.cityName cn,count(*) cnt from sykj_savings_itemgive t  "
				+ "left join sykj_savings_usercarditem t2 on t.userCardId=t2.id  "
				+ "left join sykj_area_shop t3 on t3.shortNumber = SUBSTRING_INDEX(SUBSTRING(t2.fldMemberCardTypeCode,13),'-',1) "
				+ "left join sykj_area_city t4 on t4.ID=t3.cityId "
				+ "where t.itemId='83b94b27-7c1a-48fc-a136-04a745aa39b3' and t.`status`in(1,2)  "
				+ "GROUP BY DATE_FORMAT(t.updatedatetime,'%Y-%m-%d'),t4.cityName ) A "
				+ "group by A.d  "
				+ "order by A.d desc) K on J.time = K.time "
				+ "left JOIN "
				+ "(select d as time , "
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',"
				+ "sum(if(cn='佛山市',cnt,0)) as '佛山市',sum(if(cn='广州市',cnt,0)) as '广州市',"
				+ "sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',"
				+ "sum(if(cn='上海市',cnt,0)) as '上海市',sum(if(cn='西安市',cnt,0)) as '西安市',"
				+ "sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "FROM "
				+ "(select DATE_FORMAT(t3.usetime,'%Y-%m-%d') d,t5.cityname cn,count(*) cnt from sykj_savings_usercarditem t  "
				+ "inner join sykj_savings_itemgive t2 on t.id = t2.userCardId  "
				+ "inner join sykj_savings_itemgiveuse t3 on t2.id = t3.itemgiveId  "
				+ "inner join sykj_area_shop t4 on t4.id = t3.shopId "
				+ "inner join sykj_area_city t5 on t5.id = t4.cityid "
				+ "where t.itemid = '83b94b27-7c1a-48fc-a136-04a745aa39b3' and t.status = 3 "
				+ "group by DATE_FORMAT(t3.usetime,'%Y-%m-%d'),t5.cityname) A  "
				+ "group by A.d "
				+ "order by A.d desc) L on L.time = J.time";
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

	@Override
	public List<Object> roseBuy_198() {
		// TODO Auto-generated method stub
		String sql = "select M.time,"
//				+ "IFNULL(N.珠海市,0),IFNULL(M.珠海市,0),IFNULL(N.中山市,0),IFNULL(M.中山市,0),"
//				+ "IFNULL(N.佛山市,0),IFNULL(M.佛山市,0),IFNULL(N.广州市,0),IFNULL(M.广州市,0),"
//				+ "IFNULL(N.深圳市,0),IFNULL(M.深圳市,0),IFNULL(N.海口市,0),IFNULL(M.海口市,0),"
//				+ "IFNULL(N.北京市,0),IFNULL(M.北京市,0),IFNULL(N.天津市,0),IFNULL(M.天津市,0),"
//				+ "IFNULL(N.上海市,0),IFNULL(M.上海市,0),IFNULL(N.西安市,0),IFNULL(M.西安市,0),"
//				+ "IFNULL(N.成都市,0),IFNULL(M.成都市,0),IFNULL(N.重庆市,0),IFNULL(M.重庆市,0) "
				+ "IFNULL(N.珠海市,0),IFNULL(N.中山市,0),IFNULL(N.佛山市,0),"
				+ "IFNULL(N.广州市,0),IFNULL(N.深圳市,0),IFNULL(N.海口市,0),"
				+ "IFNULL(N.北京市,0),IFNULL(N.天津市,0),IFNULL(N.上海市,0),"
				+ "IFNULL(N.西安市,0),IFNULL(N.成都市,0),IFNULL(N.重庆市,0),"
				+ "IFNULL(M.珠海市,0),IFNULL(M.中山市,0),IFNULL(M.佛山市,0),"
				+ "IFNULL(M.广州市,0),IFNULL(M.深圳市,0),IFNULL(M.海口市,0),"
				+ "IFNULL(M.北京市,0),IFNULL(M.天津市,0),IFNULL(M.上海市,0),"
				+ "IFNULL(M.西安市,0),IFNULL(M.成都市,0),IFNULL(M.重庆市,0) "
				+ "FROM "
				+ "(select d as time , "
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',"
				+ "sum(if(cn='佛山市',cnt,0)) as '佛山市',sum(if(cn='广州市',cnt,0)) as '广州市',"
				+ "sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',"
				+ "sum(if(cn='上海市',cnt,0)) as '上海市',sum(if(cn='西安市',cnt,0)) as '西安市',"
				+ "sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "from (select DATE_FORMAT(t1.createtime,'%Y-%m-%d') d,t3.cityname cn,count(*) cnt "
				+ "from (select mobile,companycode,createtime from ("
				+ "select mobile,companycode,createtime from sykj_erp_unboundcard "
				+ "where membercardtypecode in ('2016.02.001') "
				+ "and membercardcode not in (select membercardcode from sykj_tempcardcode) order by createtime asc ) t "
				+ "group by mobile,companycode,createtime order by createtime asc) t1 "
				+ "inner join sykj_area_shop t2 on t1.companycode = t2.shortnumber "
				+ "inner join sykj_area_city t3 on t3.id = t2.cityid "
				+ "group by DATE_FORMAT(t1.createtime,'%Y-%m-%d'),t3.cityname) A "
				+ "group by A.d "
				+ "order by A.d desc) M "
				+ "left join "
				+ "(select d as time,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',"
				+ "sum(if(cn='佛山市',cnt,0)) as '佛山市',sum(if(cn='广州市',cnt,0)) as '广州市',"
				+ "sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',"
				+ "sum(if(cn='上海市',cnt,0)) as '上海市',sum(if(cn='西安市',cnt,0)) as '西安市',"
				+ "sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "FROM "
				+ "(select DATE_FORMAT(t.buydatetime,'%Y-%m-%d') d,t5.cityname cn,count(*) cnt from sykj_savings_usercard t  "
				+ "inner join sykj_savings_itemgive t2 on t.id = t2.userCardId  "
				+ "inner join sykj_savings_itemgiveuse t3 on t2.id = t3.itemgiveId  "
				+ "inner join sykj_area_shop t4 on t4.id = t3.shopId  "
				+ "inner join sykj_area_city t5 on t5.id = t4.cityid  "
				+ "where t.cardid = 'iuioe33f-542d-4629-ab83-989898ww198' "
				+ "and t.fromOpenId is null and t.status = 3  "
				+ "group by DATE_FORMAT(t.buydatetime,'%Y-%m-%d'),t5.cityname) A "
				+ "group by A.d "
				+ "order by A.d desc) N on M.time = N.time";
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

	@Override
	public List<Object> roseSend_198() {
		// TODO Auto-generated method stub
		String sql = "select M.time,IFNULL(N.珠海市,0),IFNULL(N.中山市,0),IFNULL(N.佛山市,0),IFNULL(N.广州市,0),"
				+ "IFNULL(N.深圳市,0),IFNULL(N.海口市,0),IFNULL(N.北京市,0),IFNULL(N.天津市,0),IFNULL(N.上海市,0),"
				+ "IFNULL(N.西安市,0),IFNULL(N.成都市,0),IFNULL(N.重庆市,0),IFNULL(M.珠海市,0),IFNULL(M.中山市,0),"
				+ "IFNULL(M.佛山市,0),IFNULL(M.广州市,0),IFNULL(M.深圳市,0),IFNULL(M.海口市,0),IFNULL(M.北京市,0),"
				+ "IFNULL(M.天津市,0),IFNULL(M.上海市,0),IFNULL(M.西安市,0),IFNULL(M.成都市,0),IFNULL(M.重庆市,0) "
				+ "FROM "
				+ "(select d as time ,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',"
				+ "sum(if(cn='佛山市',cnt,0)) as '佛山市',sum(if(cn='广州市',cnt,0)) as '广州市',"
				+ "sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',"
				+ "sum(if(cn='上海市',cnt,0)) as '上海市',sum(if(cn='西安市',cnt,0)) as '西安市',"
				+ "sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "FROM "
				+ "(select DATE_FORMAT(t3.useTime,'%Y-%m-%d') d,t5.cityname cn,count(*) cnt from sykj_savings_usercard t "
				+ "inner join sykj_savings_itemgive t2 on t.id = t2.userCardId "
				+ "inner join sykj_savings_itemgiveuse t3 on t2.id = t3.itemgiveId "
				+ "inner join sykj_area_shop t4 on t3.shopId = t4.ID "
				+ "inner join sykj_area_city t5 on t4.cityid = t5.id "
				+ "where t.cardid = 'iuioe33f-542d-4629-ab83-989898ww198' and t.fromOpenId is NULL "
				+ "and t.status = 3 "
				+ "group by DATE_FORMAT(t3.useTime,'%Y-%m-%d'),t5.cityname) A "
				+ "group by A.d "
				+ "order by A.d desc) M "
				+ "LEFT JOIN "
				+ "(select d as time,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',"
				+ "sum(if(cn='佛山市',cnt,0)) as '佛山市',sum(if(cn='广州市',cnt,0)) as '广州市',"
				+ "sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',"
				+ "sum(if(cn='上海市',cnt,0)) as '上海市',sum(if(cn='西安市',cnt,0)) as '西安市',"
				+ "sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "FROM "
				+ "(select DATE_FORMAT(t.receiveTime,'%Y-%m-%d') d,t5.cityname cn,count(*) cnt from sykj_savings_usercard t  "
				+ "inner join sykj_savings_itemgive t2 on t.fromUserCardId = t2.userCardId "
				+ "inner join sykj_savings_itemgiveuse t3 on t2.id = t3.itemgiveId "
				+ "inner join sykj_area_shop t4 on t3.shopid = t4.ID "
				+ "inner join sykj_area_city t5 on t5.id = t4.cityId "
				+ "where t.cardid = 'iuioe33f-542d-4629-ab83-989898ww198' and t.fromopenid is not null "
				+ "and t.`status` = 3 "
				+ "group by DATE_FORMAT(t.receiveTime,'%Y-%m-%d'),t5.cityname) A "
				+ "group by A.d "
				+ "order by A.d desc) N on M.time = N.time";
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

	@Override
	public List<Object> chouJiang() {
		// TODO Auto-generated method stub
		String sql = "select M.*,IFNULL(N.套盒,0),IFNULL(N.spa,0),"
				+ "IFNULL(N.复活草,0),IFNULL(N.精油,0),IFNULL(N.现金券,0) "
				+ "from "
				+ "(select d as time,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',"
				+ "sum(if(cn='佛山市',cnt,0)) as '佛山市',sum(if(cn='广州市',cnt,0)) as '广州市',"
				+ "sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',"
				+ "sum(if(cn='上海市',cnt,0)) as '上海市',sum(if(cn='西安市',cnt,0)) as '西安市',"
				+ "sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "FROM "
				+ "(select DATE_FORMAT(t.winningTime,'%Y-%m-%d') d,t5.cityname cn,count(*) cnt from sykj_luckdraw_userprize t "
				+ "inner join sykj_user_userinformation t2 on t.userOpenId = t2.openId "
				+ "inner join (select a.mobile,a.companycode,a.createtime from  "
				+ "(select * from sykj_erp_unboundcard order by createtime asc) a "
				+ "group by a.mobile) t3 on t3.mobile = t2.mobile "
				+ "inner join sykj_area_shop t4 on t4.shortnumber = t3.companycode "
				+ "inner join sykj_area_city t5 on t5.id = t4.cityId "
				+ "where t.fromtype = '玫瑰女人节' and DATE_FORMAT(t.winningTime,'%Y-%m-%d') < DATE_FORMAT(SYSDATE(),'%Y-%m-%d') "
				+ "group by DATE_FORMAT(t.winningTime,'%Y-%m-%d'),t5.cityname) A "
				+ "group by A.d "
				+ "order by A.d desc) M "
				+ "LEFT JOIN "
				+ "(SELECT d as time, "
				+ "sum(if(n='玫瑰洗护润一套',cnt,0)) as '套盒',sum(if(n='玫瑰水润SPA护理',cnt,0)) as 'spa'"
				+ ",sum(if(n='复活草头皮水润按摩',cnt,0)) as '复活草',sum(if(n='95ml 玫瑰精油洗发露',cnt,0)) as '精油',"
				+ "sum(if(n='5元现金券',cnt,0)) as '现金券' "
				+ "FROM "
				+ "(select DATE_FORMAT(t.winningTime,'%Y-%m-%d') d,t2.name n,count(*) cnt from sykj_luckdraw_userprize t  "
				+ "inner join sykj_luckdraw_prizeinfomation t2 on t.prizeId = t2.id "
				+ "where t.fromType = '玫瑰女人节' and DATE_FORMAT(t.winningTime,'%Y-%m-%d') < DATE_FORMAT(SYSDATE(),'%Y-%m-%d') "
				+ "group by DATE_FORMAT(t.winningTime,'%Y-%m-%d'),t2.name) A "
				+ "group by A.d "
				+ "order by A.d desc) N on M.time = N.time";
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

	@Override
	public List<Object> twelve() {
		// TODO Auto-generated method stub
		String sql = "select d as time,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',"
				+ "sum(if(cn='佛山市',cnt,0)) as '佛山市',sum(if(cn='广州市',cnt,0)) as '广州市',"
				+ "sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',"
				+ "sum(if(cn='上海市',cnt,0)) as '上海市',sum(if(cn='西安市',cnt,0)) as '西安市',"
				+ "sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "FROM "
				+ "(select DATE_FORMAT(t.CREATEDATETIME,'%Y-%m-%d') d,t4.cityname cn,count(*) cnt from sykj_user_tuser t  "
				+ "inner join (select t.mobile,t.companycode,t.createtime from  "
				+ "(select * from sykj_erp_unboundcard order by createtime asc) t "
				+ "group by t.mobile) t2 on t.USERNAME = t2.mobile "
				+ "inner join sykj_area_shop t3 on t3.shortnumber = t2.companycode "
				+ "inner join sykj_area_city t4 on t4.id = t3.cityId "
				+ "where DATE_FORMAT(t.CREATEDATETIME, '%Y-%m-%d') > '2016-03-03'  "
				+ "and DATE_FORMAT(t.CREATEDATETIME,'%Y-%m-%d') < DATE_FORMAT(SYSDATE(),'%Y-%m-%d') "
				+ "group by DATE_FORMAT(t.CREATEDATETIME,'%Y-%m-%d'),t4.cityname) A "
				+ "group by A.d "
				+ "order by A.d desc";
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

	@Override
	public List<Object> buy_98() {
		// TODO Auto-generated method stub
		String sql = "select K.time,"
				+ "IFNULL(M.珠海市,0),IFNULL(M.中山市,0),IFNULL(M.佛山市,0),"
				+ "IFNULL(M.广州市,0),IFNULL(M.深圳市,0),IFNULL(M.海口市,0),"
				+ "IFNULL(M.北京市,0),IFNULL(M.天津市,0),IFNULL(M.上海市,0),"
				+ "IFNULL(M.西安市,0),IFNULL(M.成都市,0),IFNULL(M.重庆市,0),"
				+ "IFNULL(N.珠海市,0),IFNULL(N.中山市,0),IFNULL(N.佛山市,0),"
				+ "IFNULL(N.广州市,0),IFNULL(N.深圳市,0),IFNULL(N.海口市,0),"
				+ "IFNULL(N.北京市,0),IFNULL(N.天津市,0),IFNULL(N.上海市,0),"
				+ "IFNULL(N.西安市,0),IFNULL(N.成都市,0),IFNULL(N.重庆市,0) "
				+ "from "
				+ "("
				+ "select DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') time from sykj_user_tuser "
				+ "where DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') >= '2016-06-18' "
				+ "and DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') < DATE_FORMAT(SYSDATE(),'%Y-%m-%d') "
				+ "group by DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') "
				+ "ORDER BY DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') desc"
				+ ") K "
				+ "LEFT JOIN "
				+ "( "
				+ "select d as time,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',sum(if(cn='佛山市',cnt,0)) as '佛山市',"
				+ "sum(if(cn='广州市',cnt,0)) as '广州市',sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',sum(if(cn='上海市',cnt,0)) as '上海市',"
				+ "sum(if(cn='西安市',cnt,0)) as '西安市',sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "from "
				+ "("
				+ "select DATE_FORMAT(t.buydatetime,'%Y-%m-%d') d,t5.cityname cn,count(*) cnt "
				+ "from ("
				+ "select * from sykj_savings_usercard "
				+ "where cardId = '182dbaa5-1d05-4ac5-b587-5f3774814c15' "
				+ "and fromUserCardId is null and status = 3 "
				+ "and DATE_FORMAT(buyDateTime,'%Y-%m-%d') < DATE_FORMAT(SYSDATE(),'%Y-%m-%d') "
				+ ") t "
				+ "inner join sykj_savings_itemgive t2 on t.id = t2.userCardId "
				+ "inner join sykj_savings_itemgiveuse t3 on t2.id = t3.itemgiveId "
				+ "inner join sykj_area_shop t4 on t4.id = t3.shopId "
				+ "inner join sykj_area_city t5 on t5.id = t4.cityId "
//				+ "inner join ("
//				+ "select * from sykj_mall_order "
//				+ "where cityGroup = '618' and ORDERTYPE = 2 "
//				+ "and status = 1 and AMOUNT = 98 "
//				+ ") t6 on t.mobile = t6.SENDPHONE "
				+ "where t.shareRecordid = '' "
				+ "group by DATE_FORMAT(t.buyDateTime,'%Y-%m-%d'),t5.cityname "
				+ ") A "
				+ "group by A.d "
				+ "order by A.d desc "
				+ ") M on K.time = M.time "
				+ "LEFT JOIN "
				+ "("
				+ "select d as time,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',sum(if(cn='佛山市',cnt,0)) as '佛山市',"
				+ "sum(if(cn='广州市',cnt,0)) as '广州市',sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',sum(if(cn='上海市',cnt,0)) as '上海市',"
				+ "sum(if(cn='西安市',cnt,0)) as '西安市',sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "from ("
				+ "select DATE_FORMAT(t.buydatetime,'%Y-%m-%d') d,t5.cityname cn,count(*) cnt "
				+ "from ("
				+ "select * from sykj_savings_usercard "
				+ "where cardId = '182dbaa5-1d05-4ac5-b587-5f3774814c15' "
				+ "and fromUserCardId is null and status = 3 "
				+ "and DATE_FORMAT(buyDateTime,'%Y-%m-%d') < DATE_FORMAT(SYSDATE(),'%Y-%m-%d') "
				+ ") t "
				+ "inner join sykj_savings_itemgive t2 on t.id = t2.userCardId "
				+ "inner join sykj_savings_itemgiveuse t3 on t2.id = t3.itemgiveId "
				+ "inner join sykj_area_shop t4 on t4.id = t3.shopId "
				+ "inner join sykj_area_city t5 on t5.id = t4.cityId "
//				+ "inner join ("
//				+ "select * from sykj_mall_order "
//				+ "where cityGroup = '618' and ORDERTYPE = 2 "
//				+ "and status = 1 and AMOUNT = 88 "
//				+ ") t6 on t.mobile = t6.SENDPHONE "
				+ "where t.shareRecordid != '' "
				+ "group by DATE_FORMAT(t.buyDateTime,'%Y-%m-%d'),t5.cityname "
				+ ") A "
				+ "group by A.d "
				+ "order by A.d desc "
				+ ") N on K.time = N.time";
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

	@Override
	public List<Object> send_98() {
		// TODO Auto-generated method stub
		String sql = "select K.time,"
				+ "IFNULL(M.珠海市,0),IFNULL(M.中山市,0),IFNULL(M.佛山市,0),"
				+ "IFNULL(M.广州市,0),IFNULL(M.深圳市,0),IFNULL(M.海口市,0),"
				+ "IFNULL(M.北京市,0),IFNULL(M.天津市,0),IFNULL(M.上海市,0),"
				+ "IFNULL(M.西安市,0),IFNULL(M.成都市,0),IFNULL(M.重庆市,0),"
				+ "IFNULL(N.珠海市,0),IFNULL(N.中山市,0),IFNULL(N.佛山市,0),"
				+ "IFNULL(N.广州市,0),IFNULL(N.深圳市,0),IFNULL(N.海口市,0),"
				+ "IFNULL(N.北京市,0),IFNULL(N.天津市,0),IFNULL(N.上海市,0),"
				+ "IFNULL(N.西安市,0),IFNULL(N.成都市,0),IFNULL(N.重庆市,0) "
				+ "from "
				+ "("
				+ "select DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') time from sykj_user_tuser "
				+ "where DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') >= '2016-06-18' and DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') < DATE_FORMAT(SYSDATE(),'%Y-%m-%d') "
				+ "group by DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') "
				+ "ORDER BY DATE_FORMAT(CREATEDATETIME,'%Y-%m-%d') desc "
				+ ") K "
				+ "LEFT JOIN "
				+ "( "
				+ "select d as time,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',sum(if(cn='佛山市',cnt,0)) as '佛山市',"
				+ "sum(if(cn='广州市',cnt,0)) as '广州市',sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',sum(if(cn='上海市',cnt,0)) as '上海市',"
				+ "sum(if(cn='西安市',cnt,0)) as '西安市',sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "FROM "
				+ "("
				+ "select DATE_FORMAT(t.receiveTime,'%Y-%m-%d') d,t5.cityname cn,count(*) cnt "
				+ "from ("
				+ "select * from sykj_savings_usercard "
				+ "where cardId = '182dbaa5-1d05-4ac5-b587-5f3774814c15' "
				+ "and fromUserCardId is not null and status = 3 "
				+ "and DATE_FORMAT(buyDateTime,'%Y-%m-%d') < DATE_FORMAT(SYSDATE(),'%Y-%m-%d') "
				+ ") t "
				+ "inner join sykj_savings_itemgive t2 on t.fromUserCardId = t2.userCardId "
				+ "inner join sykj_savings_itemgiveuse t3 on t2.id = t3.itemgiveId "
				+ "inner join sykj_area_shop t4 on t3.shopid = t4.ID "
				+ "inner join sykj_area_city t5 on t5.id = t4.cityId "
				+ "group by DATE_FORMAT(t.receiveTime,'%Y-%m-%d'),t5.cityname "
				+ ") A "
				+ "group by A.d "
				+ "order by A.d desc "
				+ ") M on K.time = M.time "
				+ "left JOIN "
				+ "("
				+ "select d as time ,"
				+ "sum(if(cn='珠海市',cnt,0)) as '珠海市',sum(if(cn='中山市',cnt,0)) as '中山市',sum(if(cn='佛山市',cnt,0)) as '佛山市',"
				+ "sum(if(cn='广州市',cnt,0)) as '广州市',sum(if(cn='深圳市',cnt,0)) as '深圳市',sum(if(cn='海口市',cnt,0)) as '海口市',"
				+ "sum(if(cn='北京市',cnt,0)) as '北京市',sum(if(cn='天津市',cnt,0)) as '天津市',sum(if(cn='上海市',cnt,0)) as '上海市',"
				+ "sum(if(cn='西安市',cnt,0)) as '西安市',sum(if(cn='成都市',cnt,0)) as '成都市',sum(if(cn='重庆市',cnt,0)) as '重庆市' "
				+ "FROM "
				+ "("
				+ "select DATE_FORMAT(t3.useTime,'%Y-%m-%d') d,t5.cityname cn,count(*) cnt "
				+ "from ( "
				+ "select * from sykj_savings_usercard "
				+ "where cardId = '182dbaa5-1d05-4ac5-b587-5f3774814c15' "
				+ "and fromUserCardId is null and status = 3 "
				+ "and DATE_FORMAT(buyDateTime,'%Y-%m-%d') < DATE_FORMAT(SYSDATE(),'%Y-%m-%d') "
				+ ") t "
				+ "inner join sykj_savings_itemgive t2 on t.id = t2.userCardId "
				+ "inner join sykj_savings_itemgiveuse t3 on t2.id = t3.itemgiveId "
				+ "inner join sykj_area_shop t4 on t3.shopId = t4.ID "
				+ "inner join sykj_area_city t5 on t4.cityid = t5.id "
				+ "group by DATE_FORMAT(t3.useTime,'%Y-%m-%d'),t5.cityname "
				+ ") A "
				+ "group by A.d "
				+ "order by A.d desc "
				+ ") N on K.time = N.time";
		System.out.println("sql="+sql);
		return this.findSQL(sql);
	}

}
